name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: rust
      run: cargo build --verbose --examples
    - name: Check code format
      working-directory: rust
      run: cargo fmt -- --check
    - name: Run clippy
      working-directory: rust
      run: cargo clippy --examples -- --forbid warnings
    - name: Run tests
      working-directory: rust
      run: cargo test --verbose --examples
